# services:
#   backend:
#     image: ghcr.io/meats-central/projectmeats-backend:dev-latest
#     working_dir: /app
#     volumes:
#       - ..:/app
#     ports:
#       - "8000:8000"
#     command: sleep infinity

#   frontend:
#     image: ghcr.io/meats-central/projectmeats-frontend:dev-latest
#     working_dir: /project
#     volumes:
#       - ..:/project
#     ports:
#       - "3000:3000"
#     command: sleep infinity
